[package]
name = "db"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mysql = "21.0.1"
diesel = { version = "1.4.4", features = ["mysql", "numeric"] }
dotenv = "0.15.0"
